[workspace]
authors = ["Anne Hartebrodt <anne.hartebrodt[a]fau.de>"]
channels = ["conda-forge", "bioconda", "main", "r", "msys2"]
name = "netmap-evaluation"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.8"

[tasks]
install-kernel = "python -m ipykernel install --user --name pixi_netmap --display-name pixi_netmap"


[dependencies]
pytorch-gpu = "*"
cuda-version = "12.8.*"
scikit-learn = ">=1.6.1,<2"
pandas = ">=2.3.1,<3"
scipy = ">=1.15.2,<2"
numpy = ">=2.2.6,<3"
scanpy = ">=1.11.2,<2"
anndata = ">=0.11.4,<0.12"
bioconductor-ucell = ">=2.10.1,<3"
seaborn = ">=0.13.2,<0.14"
statsmodels = ">=0.14.4,<0.15"
omnipath = ">=1.0.8,<2"
captum = ">=0.7.0,<0.8"
python-igraph = ">=0.11.8,<0.12"
leidenalg = ">=0.10.2,<0.11"
pingouin = ">=0.5.5,<0.6"
matplotlib = ">=3.10.3,<4"
ipykernel = ">=6.29.5,<7"
pyarrow = "*"
cupy = ">=13.5.1,<14"
gtfparse = ">=2.5.0,<3"
pyvis = ">=0.3.2,<0.4"


[pypi-dependencies]
netmap = { path = ".", editable = true}

