[workspace]
authors = ["Anne Hartebrodt <anne.hartebrodt[a]fau.de>"]
channels = ["conda-forge", "bioconda", "main", "r", "msys2"]
name = "netmap-evaluation"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.8"

[tasks]
install-kernel = "python -m ipykernel install --user --name pixi_netmap --display-name pixi_netmap"
uninstall-kernel = "jupyter kernelspec uninstall pixi_netmap"

[dependencies]
pytorch-gpu = "*"
cuda-version = "12.8.*"
cupy = ">=13.5.1,<14"
pooch = ">=1.8.2,<2"
scikit-image = ">=0.25.2,<0.26"
sphinx = "*"
sphinx-autobuild = "*"
furo = "*"


[pypi-dependencies]
netmap = { git = "https://github.com/bionetslab/netmap" }
