[workspace]
authors = ["Anne Hartebrodt <anne.hartebrodt[a]fau.de>"]
channels = ["nvidia", "pytorch", "conda-forge", "bioconda", "main", "r", "msys2"]
name = "netmap-lrp-scvi"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-kernel = "python -m ipykernel install --user --name pixi_netmap --display-name pixi_netmap"

[dependencies]
_openmp_mutex = "4.5.*"
alembic = "1.13.2.*"
alsa-lib = "1.2.8.*"
anndata = "0.10.9.*"
anyio = "4.4.0.*"
argon2-cffi = "23.1.0.*"
argon2-cffi-bindings = "21.2.0.*"
arpack = "3.7.0.*"
array-api-compat = "1.8.*"
arrow = "1.3.0.*"
asttokens = "2.4.1.*"
async-lru = "2.0.4.*"
attr = "2.5.1.*"
attrs = "24.2.0.*"
aws-c-auth = "0.7.0.*"
aws-c-cal = "0.6.0.*"
aws-c-common = "0.8.23.*"
aws-c-compression = "0.2.17.*"
aws-c-event-stream = "0.3.1.*"
aws-c-http = "0.7.11.*"
aws-c-io = "0.13.28.*"
aws-c-mqtt = "0.8.14.*"
aws-c-s3 = "0.3.13.*"
aws-c-sdkutils = "0.1.11.*"
aws-checksums = "0.1.16.*"
aws-crt-cpp = "0.20.3.*"
aws-sdk-cpp = "1.10.57.*"
babel = "2.14.0.*"
beautifulsoup4 = "4.12.3.*"
black = "24.8.0.*"
blas = "1.0.*"
bleach = "6.1.0.*"
bokeh = "3.5.2.*"
brotli = "1.0.9.*"
brotli-bin = "1.0.9.*"
brotli-python = "1.0.9.*"
bzip2 = "1.0.8.*"
c-ares = "1.33.1.*"
ca-certificates = "2024.8.30.*"
cached-property = "1.5.2.*"
cached_property = "1.5.2.*"
cairo = "1.16.0.*"
certifi = "2024.8.30.*"
cffi = "1.17.0.*"
charset-normalizer = "3.3.2.*"
click = "8.1.7.*"
cloudpickle = "3.0.0.*"
colorama = "0.4.6.*"
colorlog = "6.8.2.*"
comm = "0.2.2.*"
contourpy = "1.3.0.*"
cuda-cudart = "12.4.127.*"
cuda-cupti = "12.4.127.*"
cuda-libraries = "12.4.0.*"
cuda-nvrtc = "12.4.127.*"
cuda-nvtx = "12.4.127.*"
cuda-opencl = "12.6.37.*"
cuda-runtime = "12.4.0.*"
cuda-version = "12.6.*"
cycler = "0.12.1.*"
cytoolz = "0.12.3.*"
dask = "2024.8.1.*"
dask-core = "2024.8.1.*"
dask-expr = "1.1.11.*"
dbus = "1.13.6.*"
debugpy = "1.8.5.*"
decorator = "5.1.1.*"
defusedxml = "0.7.1.*"
distributed = "2024.8.1.*"
entrypoints = "0.4.*"
exceptiongroup = "1.2.2.*"
executing = "2.0.1.*"
expat = "2.6.2.*"
fftw = "3.3.10.*"
filelock = "3.15.4.*"
font-ttf-dejavu-sans-mono = "2.37.*"
font-ttf-inconsolata = "3.0.*"
font-ttf-source-code-pro = "2.38.*"
font-ttf-ubuntu = "0.83.*"
fontconfig = "2.14.2.*"
fonts-conda-ecosystem = "1.*"
fonts-conda-forge = "1.*"
fonttools = "4.53.1.*"
fqdn = "1.5.1.*"
freetype = "2.12.1.*"
fsspec = "2024.6.1.*"
get-annotations = "0.1.2.*"
gettext = "0.22.5.*"
gettext-tools = "0.22.5.*"
gflags = "2.2.2.*"
glib = "2.80.3.*"
glib-tools = "2.80.3.*"
glog = "0.6.0.*"
glpk = "5.0.*"
gmp = "6.3.0.*"
gmpy2 = "2.1.5.*"
graphite2 = "1.3.13.*"
greenlet = "3.0.3.*"
gst-plugins-base = "1.22.0.*"
gstreamer = "1.22.0.*"
gstreamer-orc = "0.4.39.*"
h11 = "0.14.0.*"
h2 = "4.1.0.*"
h5py = "3.9.0.*"
harfbuzz = "6.0.0.*"
hdf5 = "1.14.1.*"
hpack = "4.0.0.*"
httpcore = "1.0.5.*"
httpx = "0.27.2.*"
hyperframe = "6.0.1.*"
icu = "70.1.*"
idna = "3.8.*"
igraph = "0.10.3.*"
importlib-metadata = "8.4.0.*"
importlib_metadata = "8.4.0.*"
importlib_resources = "6.4.4.*"
ipykernel = ">=6.29.5,<7"
ipython = "8.26.0.*"
isoduration = "20.11.0.*"
jack = "1.9.22.*"
jedi = "0.19.1.*"
jinja2 = "3.1.4.*"
joblib = "1.4.2.*"
jpeg = "9e.*"
json5 = "0.9.25.*"
jsonpointer = "3.0.0.*"
jsonschema = "4.23.0.*"
jsonschema-specifications = "2023.12.1.*"
jsonschema-with-format-nongpl = "4.23.0.*"
jupyter-black = "0.4.0.*"
jupyter-lsp = "2.2.5.*"
jupyter_client = "8.6.2.*"
jupyter_core = "5.7.2.*"
jupyter_events = "0.10.0.*"
jupyter_server = "2.14.2.*"
jupyter_server_terminals = "0.5.3.*"
jupyterlab = ">=4.4.2,<5"
jupyterlab_pygments = "0.3.0.*"
jupyterlab_server = "2.27.3.*"
keyutils = "1.6.1.*"
kiwisolver = "1.4.5.*"
krb5 = "1.20.1.*"
lame = "3.100.*"
lcms2 = "2.15.*"
ld_impl_linux-64 = "2.40.*"
legacy-api-wrap = "1.4.*"
leidenalg = "0.9.1.*"
lerc = "4.0.0.*"
libabseil = "20230125.3.*"
libaec = "1.1.3.*"
libarrow = "12.0.1.*"
libasprintf = "0.22.5.*"
libasprintf-devel = "0.22.5.*"
libblas = "3.9.0.*"
libbrotlicommon = "1.0.9.*"
libbrotlidec = "1.0.9.*"
libbrotlienc = "1.0.9.*"
libcap = "2.67.*"
libcblas = "3.9.0.*"
libclang = "15.0.7.*"
libclang13 = "15.0.7.*"
libcrc32c = "1.1.2.*"
libcublas = "12.4.2.65.*"
libcufft = "11.2.0.44.*"
libcufile = "1.11.0.15.*"
libcups = "2.3.3.*"
libcurand = "10.3.7.37.*"
libcurl = "8.1.2.*"
libcusolver = "11.6.0.99.*"
libcusparse = "12.3.0.142.*"
libdb = "6.2.32.*"
libdeflate = "1.17.*"
libedit = "3.1.20191231.*"
libev = "4.33.*"
libevent = "2.1.10.*"
libexpat = "2.6.2.*"
libffi = "3.4.2.*"
libflac = "1.4.3.*"
libgcc = "14.1.0.*"
libgcc-ng = "14.1.0.*"
libgcrypt = "1.11.0.*"
libgettextpo = "0.22.5.*"
libgettextpo-devel = "0.22.5.*"
libgfortran = "14.1.0.*"
libgfortran-ng = "14.1.0.*"
libgfortran5 = "14.1.0.*"
libglib = "2.80.3.*"
libgoogle-cloud = "2.12.0.*"
libgpg-error = "1.50.*"
libgrpc = "1.56.2.*"
libhwloc = "2.9.1.*"
libiconv = "1.17.*"
liblapack = "3.9.0.*"
libllvm14 = "14.0.6.*"
libllvm15 = "15.0.7.*"
libnghttp2 = "1.58.0.*"
libnpp = "12.2.5.2.*"
libnsl = "2.0.1.*"
libnuma = "2.0.18.*"
libnvfatbin = "12.6.20.*"
libnvjitlink = "12.4.99.*"
libnvjpeg = "12.3.1.89.*"
libogg = "1.3.5.*"
libopus = "1.3.1.*"
libpng = "1.6.43.*"
libpq = "15.3.*"
libprotobuf = "4.23.3.*"
libsndfile = "1.2.2.*"
libsodium = "1.0.18.*"
libsqlite = "3.46.0.*"
libssh2 = "1.11.0.*"
libstdcxx = "14.1.0.*"
libstdcxx-ng = "14.1.0.*"
libsystemd0 = "253.*"
libthrift = "0.18.1.*"
libtiff = "4.5.0.*"
libtool = "2.4.7.*"
libudev1 = "253.*"
libutf8proc = "2.8.0.*"
libuuid = "2.38.1.*"
libvorbis = "1.3.7.*"
libwebp-base = "1.4.0.*"
libxcb = "1.13.*"
libxkbcommon = "1.5.0.*"
libxml2 = "2.10.3.*"
libzlib = "1.3.1.*"
llvm-openmp = "15.0.7.*"
llvmlite = "0.43.0.*"
locket = "1.0.0.*"
lz4 = "4.3.3.*"
lz4-c = "1.9.4.*"
mako = "1.3.5.*"
markupsafe = "2.1.5.*"
matplotlib = "3.9.1.*"
matplotlib-base = "3.9.1.*"
matplotlib-inline = "0.1.7.*"
metis = "5.1.0.*"
mistune = "3.0.2.*"
mkl = "2022.2.1.*"
mpc = "1.3.1.*"
mpfr = "4.2.1.*"
mpg123 = "1.32.6.*"
mpmath = "1.3.0.*"
msgpack-python = "1.0.8.*"
munkres = "1.1.4.*"
mypy_extensions = "1.0.0.*"
mysql-common = "8.0.33.*"
mysql-libs = "8.0.33.*"
natsort = "8.4.0.*"
nbclient = "0.10.0.*"
nbconvert-core = "7.16.4.*"
nbformat = "5.10.4.*"
ncurses = "6.5.*"
nest-asyncio = "1.6.0.*"
networkx = "3.3.*"
notebook-shim = "0.2.4.*"
nspr = "4.35.*"
nss = "3.103.*"
numba = "0.60.0.*"
numpy = "1.26.4.*"
openjpeg = "2.5.0.*"
openssl = "3.1.6.*"
optuna = "3.6.1.*"
orc = "1.9.0.*"
overrides = "7.7.0.*"
packaging = "24.1.*"
pandas = "2.2.2.*"
pandocfilters = "1.5.0.*"
parso = "0.8.4.*"
partd = "1.4.2.*"
pathspec = "0.12.1.*"
patsy = "0.5.6.*"
pcre2 = "10.44.*"
pexpect = "4.9.0.*"
pickleshare = "0.7.5.*"
pillow = "9.4.0.*"
pip = ">=25.1.1,<26"
pixman = "0.43.2.*"
pkgutil-resolve-name = "1.3.10.*"
platformdirs = "4.2.2.*"
ply = "3.11.*"
prometheus_client = "0.20.0.*"
prompt-toolkit = "3.0.47.*"
psutil = "6.0.0.*"
pthread-stubs = "0.4.*"
ptyprocess = "0.7.0.*"
pulseaudio = "16.1.*"
pulseaudio-client = "16.1.*"
pulseaudio-daemon = "16.1.*"
pure_eval = "0.2.3.*"
pyarrow = "12.0.1.*"
pyarrow-hotfix = "0.6.*"
pycparser = "2.22.*"
pygments = "2.18.0.*"
pynndescent = "0.5.13.*"
pyparsing = "3.1.4.*"
pyqt = "5.15.9.*"
pyqt5-sip = "12.12.2.*"
pysocks = "1.7.1.*"
python = "3.11.6.*"
python-dateutil = "2.9.0.*"
python-fastjsonschema = "2.20.0.*"
python-igraph = "0.10.4.*"
python-json-logger = "2.0.7.*"
python-tzdata = "2024.1.*"
python_abi = "3.11.*"
pytorch = "2.4.0.*"
pytorch-cuda = "12.4.*"
pytorch-mutex = "1.0.*"
pytz = "2024.1.*"
pyyaml = "6.0.2.*"
pyzmq = "26.2.0.*"
qhull = "2020.2.*"
qt-main = "5.15.8.*"
rdma-core = "28.9.*"
re2 = "2023.3.2.*"
readline = "8.2.*"
referencing = "0.35.1.*"
requests = "2.32.3.*"
rfc3339-validator = "0.1.4.*"
rfc3986-validator = "0.1.1.*"
rpds-py = "0.20.0.*"
s2n = "1.3.46.*"
scanpy = "1.10.2.*"
scikit-learn = "1.5.1.*"
scipy = "1.14.1.*"
seaborn = "0.13.2.*"
seaborn-base = "0.13.2.*"
send2trash = "1.8.3.*"
session-info = "1.0.0.*"
setuptools = "72.2.0.*"
sip = "6.7.12.*"
six = "1.16.0.*"
snappy = "1.1.10.*"
sniffio = "1.3.1.*"
sortedcontainers = "2.4.0.*"
soupsieve = "2.5.*"
sqlalchemy = "2.0.32.*"
stack_data = "0.6.2.*"
statsmodels = "0.14.2.*"
stdlib-list = "0.10.0.*"
suitesparse = "5.10.1.*"
sympy = "1.13.2.*"
tbb = "2021.9.0.*"
tblib = "3.0.0.*"
terminado = "0.18.1.*"
texttable = "1.7.0.*"
threadpoolctl = "3.5.0.*"
tinycss2 = "1.3.0.*"
tk = "8.6.13.*"
tokenize-rt = "6.0.0.*"
toml = "0.10.2.*"
tomli = "2.0.1.*"
toolz = "0.12.1.*"
torchtriton = "3.0.0.*"
tornado = "6.4.1.*"
tqdm = "4.66.5.*"
traitlets = "5.14.3.*"
types-python-dateutil = "2.9.0.20240821.*"
typing-extensions = "4.12.2.*"
typing_extensions = "4.12.2.*"
typing_utils = "0.1.0.*"
tzdata = "2024a.*"
ucx = "1.14.1.*"
umap-learn = "0.5.6.*"
uri-template = "1.3.0.*"
urllib3 = "2.2.2.*"
wcwidth = "0.2.13.*"
webcolors = "24.8.0.*"
webencodings = "0.5.1.*"
websocket-client = "1.8.0.*"
wheel = "0.44.0.*"
xcb-util = "0.4.0.*"
xcb-util-image = "0.4.0.*"
xcb-util-keysyms = "0.4.0.*"
xcb-util-renderutil = "0.3.9.*"
xcb-util-wm = "0.4.1.*"
xkeyboard-config = "2.38.*"
xorg-kbproto = "1.0.7.*"
xorg-libice = "1.1.1.*"
xorg-libsm = "1.2.4.*"
xorg-libx11 = "1.8.4.*"
xorg-libxau = "1.0.11.*"
xorg-libxdmcp = "1.1.3.*"
xorg-libxext = "1.3.4.*"
xorg-libxrender = "0.9.10.*"
xorg-renderproto = "0.11.1.*"
xorg-xextproto = "7.3.0.*"
xorg-xproto = "7.0.31.*"
xyzservices = "2024.6.0.*"
xz = "5.2.6.*"
yaml = "0.2.5.*"
zeromq = "4.3.5.*"
zict = "3.0.0.*"
zipp = "3.20.1.*"
zstandard = "0.23.0.*"
zstd = "1.5.6.*"
scvi-tools = "*"

[pypi-dependencies]
pypiper = ">=0.5.3, <0.6"
